DEFAULT_CONFIG = {
    "GreedAndFearLimit": 10,
    "ReverseTrendCheckBackSeconds": 600,
    "ReverseTrendCheckMinCount": 60,
    "SantimentThreshold": 1.0,
    "ReverseTrendCheckPercentageAgreeThreshold": 100,
    "SantimentFromTimeDaysAgo": 36,
    "SantimentToTimeDaysAgo": 30,
    "SantimentThresholdLong": 0.25,
    "SantimentThresholdShort": -0.25,
    "ReturnOnInvest": 0.08,
    "ReverseTrendShouldBeNegativePercent": 100,
    "ReverseTrendCheckFirstGreater": "true",
    "ReverseTrendCheckLinearDecreasing": "true",
    "ReverseTrendLinearDecreasingThresholdPercent": 95,
    "WinrateHigh": 0.7,
    "WinrateLow": 0.3,
    "StoplossWinrateHigh": -0.12,
    "StoplossWinrateLow": -0.18,
    "StoplossWinrateNeutral": -0.18,
    "MaxStake": 1000,
    "MinStake": 10,
    "DefaultStake": 100,
    "StakeIncrementStep": 100,
    "Leverage": 5.0,
    "BiasSymbols": "BTC",
    "BiasShowAll": "true"
}
